"""Added new tables

Revision ID: 143a0d8271b9
Revises: 32578c6b4504
Create Date: 2025-09-13 15:41:28.686211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143a0d8271b9'
down_revision = '32578c6b4504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('cover_url')

    # ### end Alembic commands ###
