"""cover image added

Revision ID: f7c6e74244c6
Revises: 47c649a04ad5
Create Date: 2025-09-23 23:51:19.842883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c6e74244c6'
down_revision = '47c649a04ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_bookmarks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'blog_id')
    )
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excerpt', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cover_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reading_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_column('views')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('reading_time')
        batch_op.drop_column('category')
        batch_op.drop_column('tags')
        batch_op.drop_column('cover_image')
        batch_op.drop_column('excerpt')

    op.drop_table('blog_bookmarks')
    # ### end Alembic commands ###
